window.SEED_PRODUCTS = [
  { id:"p1", name:"Kit Arduino básico", price:450, category:"electronica", tag:"Nuevo",
    desc:"Incluye Arduino UNO (genérico), protoboard y jumpers. Ideal para prácticas.",
  },
  { id:"p2", name:"Sensor ultrasónico HC-SR04", price:120, category:"electronica", tag:"Oferta",
    desc:"Sensor de distancia. Perfecto para proyectos de robótica (legales, no trampa).",
  },
  { id:"p3", name:"Pack de LEDs + resistencias", price:90, category:"electronica", tag:"",
    desc:"LEDs variados + resistencias comunes. Para no andar mendigando en el laboratorio.",
  },
  { id:"p4", name:"Impresión 3D (pieza pequeña)", price:80, category:"servicio", tag:"Nuevo",
    desc:"Impresión 3D de pieza pequeña (PLA). Entrega en campus. Diseño del cliente.",
  },
  { id:"p5", name:"Instalación de software", price:200, category:"servicio", tag:"",
    desc:"Instalación y configuración básica de software (legal). Incluye drivers y ajustes.",
  },
  { id:"p6", name:"Revisión laptop (limpieza básica)", price:300, category:"servicio", tag:"Oferta",
    desc:"Limpieza básica, revisión de temperatura y recomendación de mantenimiento.",
  },
  { id:"p7", name:"Brownies caseros (4 pzas)", price:50, category:"comida", tag:"Nuevo",
    desc:"Brownies caseros. Endulza el semestre (sin reprobar, o sea, casi).",
  },
  { id:"p8", name:"Burrito de desayuno", price:45, category:"comida", tag:"",
    desc:"Burrito de desayuno listo para recoger. Energía para sobrevivir a clases.",
  },
];
